apiVersion: v1
kind: Service
metadata:
  name: pod1-service
spec:
  selector:
    app: pod1
  ports:
    - protocol: TCP
      port: 8080 
      targetPort: 3000
  type: LoadBalancer

---

apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: pod1-container
      image: georgesgil/pod1:latest
      resources:
        limits:
          cpu: "0.5"
          memory: "512Mi"
      ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod1
  template:
    metadata:
      labels:
        app: pod1
    spec:
      containers:
        - name: pod1-container
          image: georgesgil/pod1:latest
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
          ports:
            - containerPort: 3000
